package com.jorgepatrick;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class NumberConverterTest {
    private NumberConverter numberConverter;
    @Mock
    private RomanNumber romanNumber;

    @BeforeEach
    public void setup(){
        numberConverter = new NumberConverter(romanNumber);
    }

    @ParameterizedTest
    @MethodSource("provideRomanNumbersForConversion")
    public void convertToRoman(int arabicNumber, String romanNumberStr) {
        assertEquals(romanNumberStr, numberConverter.parseArabicToRoman(arabicNumber));
    }
    private static Stream<Arguments> provideRomanNumbersForConversion() {
        return Stream.of(
                Arguments.of(1, "I"),
                Arguments.of(2, "II"),
                Arguments.of(3, "III"),
                Arguments.of(4, "IV"),
                Arguments.of(5, "V"),
                Arguments.of(6, "VI"),
                Arguments.of(7, "VII"),
                Arguments.of(8, "VIII"),
                Arguments.of(9, "IX"),
                Arguments.of(10, "X"),
                Arguments.of(11, "XI"),
                Arguments.of(12, "XII"),
                Arguments.of(13, "XIII"),
                Arguments.of(14, "XIV"),
                Arguments.of(15, "XV"),
                Arguments.of(16, "XVI"),
                Arguments.of(17, "XVII"),
                Arguments.of(18, "XVIII"),
                Arguments.of(19, "XIX"),
                Arguments.of(20, "XX"),
                Arguments.of(21, "XXI"),
                Arguments.of(22, "XXII"),
                Arguments.of(23, "XXIII"),
                Arguments.of(24, "XXIV"),
                Arguments.of(25, "XXV"),
                Arguments.of(26, "XXVI"),
                Arguments.of(27, "XXVII"),
                Arguments.of(28, "XXVIII"),
                Arguments.of(29, "XXIX"),
                Arguments.of(30, "XXX"),
                Arguments.of(31, "XXXI"),
                Arguments.of(32, "XXXII"),
                Arguments.of(33, "XXXIII"),
                Arguments.of(34, "XXXIV"),
                Arguments.of(35, "XXXV"),
                Arguments.of(36, "XXXVI"),
                Arguments.of(37, "XXXVII"),
                Arguments.of(38, "XXXVIII"),
                Arguments.of(39, "XXXIX"),
                Arguments.of(40, "XL"),
                Arguments.of(41, "XLI"),
                Arguments.of(42, "XLII"),
                Arguments.of(43, "XLIII"),
                Arguments.of(44, "XLIV"),
                Arguments.of(45, "XLV"),
                Arguments.of(46, "XLVI"),
                Arguments.of(47, "XLVII"),
                Arguments.of(48, "XLVIII"),
                Arguments.of(49, "XLIX"),
                Arguments.of(50, "L"),
                Arguments.of(51, "LI"),
                Arguments.of(52, "LII"),
                Arguments.of(53, "LIII"),
                Arguments.of(54, "LIV"),
                Arguments.of(55, "LV"),
                Arguments.of(56, "LVI"),
                Arguments.of(57, "LVII"),
                Arguments.of(58, "LVIII"),
                Arguments.of(59, "LIX"),
                Arguments.of(60, "LX"),
                Arguments.of(61, "LXI"),
                Arguments.of(62, "LXII"),
                Arguments.of(63, "LXIII"),
                Arguments.of(64, "LXIV"),
                Arguments.of(65, "LXV"),
                Arguments.of(66, "LXVI"),
                Arguments.of(67, "LXVII"),
                Arguments.of(68, "LXVIII"),
                Arguments.of(69, "LXIX"),
                Arguments.of(70, "LXX"),
                Arguments.of(71, "LXXI"),
                Arguments.of(72, "LXXII"),
                Arguments.of(73, "LXXIII"),
                Arguments.of(74, "LXXIV"),
                Arguments.of(75, "LXXV"),
                Arguments.of(76, "LXXVI"),
                Arguments.of(77, "LXXVII"),
                Arguments.of(78, "LXXVIII"),
                Arguments.of(79, "LXXIX"),
                Arguments.of(80, "LXXX"),
                Arguments.of(81, "LXXXI"),
                Arguments.of(82, "LXXXII"),
                Arguments.of(83, "LXXXIII"),
                Arguments.of(84, "LXXXIV"),
                Arguments.of(85, "LXXXV"),
                Arguments.of(86, "LXXXVI"),
                Arguments.of(87, "LXXXVII"),
                Arguments.of(88, "LXXXVIII"),
                Arguments.of(89, "LXXXIX"),
                Arguments.of(90, "XC"),
                Arguments.of(91, "XCI"),
                Arguments.of(92, "XCII"),
                Arguments.of(93, "XCIII"),
                Arguments.of(94, "XCIV"),
                Arguments.of(95, "XCV"),
                Arguments.of(96, "XCVI"),
                Arguments.of(97, "XCVII"),
                Arguments.of(98, "XCVIII"),
                Arguments.of(99, "XCIX"),
                Arguments.of(100, "C"),
                Arguments.of(101, "CI"),
                Arguments.of(102, "CII"),
                Arguments.of(103, "CIII"),
                Arguments.of(104, "CIV"),
                Arguments.of(105, "CV"),
                Arguments.of(106, "CVI"),
                Arguments.of(107, "CVII"),
                Arguments.of(108, "CVIII"),
                Arguments.of(109, "CIX"),
                Arguments.of(110, "CX"),
                Arguments.of(111, "CXI"),
                Arguments.of(112, "CXII"),
                Arguments.of(113, "CXIII"),
                Arguments.of(114, "CXIV"),
                Arguments.of(115, "CXV"),
                Arguments.of(116, "CXVI"),
                Arguments.of(117, "CXVII"),
                Arguments.of(118, "CXVIII"),
                Arguments.of(119, "CXIX"),
                Arguments.of(120, "CXX"),
                Arguments.of(121, "CXXI"),
                Arguments.of(122, "CXXII"),
                Arguments.of(123, "CXXIII"),
                Arguments.of(124, "CXXIV"),
                Arguments.of(125, "CXXV"),
                Arguments.of(126, "CXXVI"),
                Arguments.of(127, "CXXVII"),
                Arguments.of(128, "CXXVIII"),
                Arguments.of(129, "CXXIX"),
                Arguments.of(130, "CXXX"),
                Arguments.of(131, "CXXXI"),
                Arguments.of(132, "CXXXII"),
                Arguments.of(133, "CXXXIII"),
                Arguments.of(134, "CXXXIV"),
                Arguments.of(135, "CXXXV"),
                Arguments.of(136, "CXXXVI"),
                Arguments.of(137, "CXXXVII"),
                Arguments.of(138, "CXXXVIII"),
                Arguments.of(139, "CXXXIX"),
                Arguments.of(140, "CXL"),
                Arguments.of(141, "CXLI"),
                Arguments.of(142, "CXLII"),
                Arguments.of(143, "CXLIII"),
                Arguments.of(144, "CXLIV"),
                Arguments.of(145, "CXLV"),
                Arguments.of(146, "CXLVI"),
                Arguments.of(147, "CXLVII"),
                Arguments.of(148, "CXLVIII"),
                Arguments.of(149, "CXLIX"),
                Arguments.of(150, "CL"),
                Arguments.of(151, "CLI"),
                Arguments.of(152, "CLII"),
                Arguments.of(153, "CLIII"),
                Arguments.of(154, "CLIV"),
                Arguments.of(155, "CLV"),
                Arguments.of(156, "CLVI"),
                Arguments.of(157, "CLVII"),
                Arguments.of(158, "CLVIII"),
                Arguments.of(159, "CLIX"),
                Arguments.of(160, "CLX"),
                Arguments.of(161, "CLXI"),
                Arguments.of(162, "CLXII"),
                Arguments.of(163, "CLXIII"),
                Arguments.of(164, "CLXIV"),
                Arguments.of(165, "CLXV"),
                Arguments.of(166, "CLXVI"),
                Arguments.of(167, "CLXVII"),
                Arguments.of(168, "CLXVIII"),
                Arguments.of(169, "CLXIX"),
                Arguments.of(170, "CLXX"),
                Arguments.of(171, "CLXXI"),
                Arguments.of(172, "CLXXII"),
                Arguments.of(173, "CLXXIII"),
                Arguments.of(174, "CLXXIV"),
                Arguments.of(175, "CLXXV"),
                Arguments.of(176, "CLXXVI"),
                Arguments.of(177, "CLXXVII"),
                Arguments.of(178, "CLXXVIII")
        );
    }
    @ParameterizedTest
    @MethodSource("provideArabicNumbersForConversion")
    public void convertToArabic(String romanNumberStr, int arabicNumber) {
        when(romanNumber.arabicNumber()).thenReturn(arabicNumber);
        assertEquals(arabicNumber, numberConverter.parseRomanToArabic(romanNumberStr));
    }
    private static Stream<Arguments> provideArabicNumbersForConversion() {
        return Stream.of(
                Arguments.of("I", 1),
                Arguments.of("II", 2),
                Arguments.of("III", 3),
                Arguments.of("IV", 4),
                Arguments.of("V", 5),
                Arguments.of("VI", 6),
                Arguments.of("VII", 7),
                Arguments.of("VIII", 8),
                Arguments.of("IX", 9),
                Arguments.of("X", 10),
                Arguments.of("XI", 11),
                Arguments.of("XII", 12),
                Arguments.of("XIII", 13),
                Arguments.of("XIV", 14),
                Arguments.of("XV", 15),
                Arguments.of("XVI", 16),
                Arguments.of("XVII", 17),
                Arguments.of("XVIII", 18),
                Arguments.of("XIX", 19),
                Arguments.of("XX", 20),
                Arguments.of("XXI", 21),
                Arguments.of("XXII", 22),
                Arguments.of("XXIII", 23),
                Arguments.of("XXIV", 24),
                Arguments.of("XXV", 25),
                Arguments.of("XXVI", 26),
                Arguments.of("XXVII", 27),
                Arguments.of("XXVIII", 28),
                Arguments.of("XXIX", 29),
                Arguments.of("XXX", 30),
                Arguments.of("XXXI", 31),
                Arguments.of("XXXII", 32),
                Arguments.of("XXXIII", 33),
                Arguments.of("XXXIV", 34),
                Arguments.of("XXXV", 35),
                Arguments.of("XXXVI", 36),
                Arguments.of("XXXVII", 37),
                Arguments.of("XXXVIII", 38),
                Arguments.of("XXXIX", 39),
                Arguments.of("XL", 40),
                Arguments.of("XLI", 41),
                Arguments.of("XLII", 42),
                Arguments.of("XLIII", 43),
                Arguments.of("XLIV", 44),
                Arguments.of("XLV", 45),
                Arguments.of("XLVI", 46),
                Arguments.of("XLVII", 47),
                Arguments.of("XLVIII", 48),
                Arguments.of("XLIX", 49),
                Arguments.of("L", 50),
                Arguments.of("LI", 51),
                Arguments.of("LII", 52),
                Arguments.of("LIII", 53),
                Arguments.of("LIV", 54),
                Arguments.of("LV", 55),
                Arguments.of("LVI", 56),
                Arguments.of("LVII", 57),
                Arguments.of("LVIII", 58),
                Arguments.of("LIX", 59),
                Arguments.of("LX", 60),
                Arguments.of("LXI", 61),
                Arguments.of("LXII", 62),
                Arguments.of("LXIII", 63),
                Arguments.of("LXIV", 64),
                Arguments.of("LXV", 65),
                Arguments.of("LXVI", 66),
                Arguments.of("LXVII", 67),
                Arguments.of("LXVIII", 68),
                Arguments.of("LXIX", 69),
                Arguments.of("LXX", 70),
                Arguments.of("LXXI", 71),
                Arguments.of("LXXII", 72),
                Arguments.of("LXXIII", 73),
                Arguments.of("LXXIV", 74),
                Arguments.of("LXXV", 75),
                Arguments.of("LXXVI", 76),
                Arguments.of("LXXVII", 77),
                Arguments.of("LXXVIII", 78),
                Arguments.of("LXXIX", 79),
                Arguments.of("LXXX", 80),
                Arguments.of("LXXXI", 81),
                Arguments.of("LXXXII", 82),
                Arguments.of("LXXXIII", 83),
                Arguments.of("LXXXIV", 84),
                Arguments.of("LXXXV", 85),
                Arguments.of("LXXXVI", 86),
                Arguments.of("LXXXVII", 87),
                Arguments.of("LXXXVIII", 88),
                Arguments.of("LXXXIX", 89)
        );
    }
}
